global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker'
    static_configs:
      - targets: ['172.17.0.1:9323']

  - job_name: 'flask_app'
    static_configs:
      - targets: [${targets}]
    metrics_path: '/metrics'
    scrape_interval: 5s
